   services:
     redis:
       image: 'redis:latest'
       ports:
         - '6379:6379'
     mysql:
       image: 'mysql:latest'
       ports:
         - '3306:3306'
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: testdb
       volumes:
         - ./init-scripts:/docker-entrypoint-initdb.d
